# Generated by Django 5.0.2 on 2024-03-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_hey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
