# Generated by Django 5.0.2 on 2024-03-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('headline', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=128)),
                ('author', models.ManyToManyField(to='news.author')),
            ],
        ),
    ]
