# Generated by Django 5.0.2 on 2024-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hey',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
