# Generated by Django 5.0.2 on 2024-03-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='password',
            field=models.CharField(default='123', max_length=30),
        ),
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default=models.CharField(max_length=30), max_length=10),
        ),
    ]
