# Generated by Django 5.0.2 on 2024-03-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_password_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
