# Generated by Django 5.0.2 on 2024-03-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_news_author_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
    ]
