# Generated by Django 5.0.2 on 2024-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('pol', 'Politics'), ('art', 'Art'), ('tech', 'Technology'), ('trivia', 'Trivial)')], default='trivia', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='region',
            field=models.CharField(choices=[('uk', 'United Kingdom'), ('eu', 'Europe'), ('w', 'World')], default='w', max_length=10),
        ),
    ]
