# Generated by Django 5.0.2 on 2024-03-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_category_news_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': "News'"},
        ),
    ]
